version: '3'
services:
  node:
    build: ./backend/.
    networks: 
      - governetwork
    ports:
      - 8080:8080
    depends_on:
      - "frontend"
  mongodb:
    build: ./database/.
    ports:
      - 27017:27017
    networks:
      - governetwork
  frontend:
    build: ./frontend/.
    ports:
      - 5000:5000
    networks:
      - governetwork
    depends_on:
      - "mongodb"

networks:
  governetwork:
    driver: bridge
